### ISSUE TITLE
Stress test prototype formulation

### ISSUE THREAD

**Issue by adowling2** [rsdefever/bondconstrain#1]
@rsdefever I'll swing by CoMSEL at 5pm. See my recent push.

**Comment by rsdefever** [comment]
I just pushed changes that incorporate everything into a single Python file. I'll work on stress testing this on larger problems next.

**Comment by adowling2** [comment]
@rsdefever Great. Other suggestions:
- Implement as a class with methods:
   - Create model
   - Solve
   - Update model
   - Extract solution
- Add optional bond angle constraints (which could get interesting... it might be impossible to meet both bond length and bond angle constraints)
- Open a PR? I could then act as a reviewer

**Comment by rsdefever** [comment]
Stress tests complete. We can address angle constraints at a later time if there is interest. Closing issue.
